# config
logo: /images/branding/Paradigm-Next-Logo.png
keywords: "Local Resilience, Adaptive Action, Peaceful Continuity, Modularity, Tribal Identity"
pubkey:

# Content
excerpt_link: Read more

# Miscellaneous
rss: /rss.xml
twitter:
google_plus:
fb_admins: 511446393
fb_app_id:

default_thumb: /images/branding/The-Positive-720p.png
breaking_thumb: /images/thumbs/breaking-news.png